### ISSUE TITLE
Downgrading pandas, matplotlib, networkx packages when installing nxviz

### ISSUE THREAD

**Issue by PyMap** [ericmjl/nxviz#655]
* nxviz version: 0.6.2
* Python version: 3.7
* Operating System: Ubuntu 20.1

### Description
While insalling nxviz from pip without specifying the version, pandas downgrade to 0.25.1, numpy to 1.17.1, matplotlib to 3.1.1 and networkx to 2.3. Versions I was using before nxviz installation were 1.2.3 (pandas), 1.20.1 (numpy), 3.3.4 (matplotlib), 2.5. (networkx).

I saw in the git repo that latest release is 0.4.0 and none of the versions I'm listing above are in the requirements.txt so I'm a bit confused from where this packages are being installed (maybe on 0.6.2 the requirements.txt specify those versions, not sure).

Just want to know if there is some update planned to install the package.

Thanks!

**Comment by ericmjl** [comment]
Hello @PyMap! Thank you for the catch. It seems like I need to cut a new release. My long paternity leave break is coming next week, which is when I'll have a bit of time to do a new release with updated dependency versions. I think what I need to do is to pin the package versions to a _minimum_ version rather than an _exact_ version, while also disabling `pyup.io` (which insists on pinning).

**Comment by PyMap** [comment]
Hi @ericmjl ! Thanks in advance for you answer. I realized this versioning stuff because I've installed `OSMnx` in my virtual environment (`venv`, not working with conda currently) and it seems that during the installation of `nxviz` when pandas, numpy, matplotlib and networkx are downgraded `OSMNx` package returns a warning with the required versions of these packages.

Matplotlib, for example, should be higher than 3.1 because of `cb.iterable(width)` deprecation. 
```
/home/federico/federico/MDG/venv/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py:563: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cb.iterable(width):
/home/federico/federico/MDG/venv/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py:611: MatplotlibDeprecationWarning: 
The is_numlike function was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use isinstance(..., numbers.Number) instead.
  if cb.is_numlike(alpha):
```
Anyway, in [this PR](https://github.com/ericmjl/nxviz/pull/644) the versions I'm listing seem to be correctly updated. Not really sure.
Do you plan to disable pyup from here](https://github.com/ericmjl/nxviz/blob/master/.pyup.yml)? Or you are working with a token for custom configuration or something? This is a [related issue](https://github.com/pyupio/pyup/issues/359)

If it is something I can try by branching from master please let me know and I can try to give it hand with the requirements versioning.

Thanks and enjoy your time off!

**Comment by ericmjl** [comment]
@PyMap thanks a ton for offering to help! I realize I let the ball drop for too long. I'm going to cut a new release, this time with minimum versions instead of exact versions. I also changed pyup's behaviour to avoid pinning in the future. A new release is coming shortly. Hopefully this all works well!

**Comment by PyMap** [comment]
@ericmjl thanks for the fix! I reinstalled and none of the libraries I mentioned above are downgraded. So I think we can close the issue for now ...
