### ISSUE TITLE
Feature Request: Edge direction by source or target node colors.

### ISSUE THREAD

**Issue by AlirezaH320** [ericmjl/nxviz#668]
Since in `nxviz` edges are plotted to a single point in target or from a single point in source node, drawing arrows is not a good idea for representing edge direction. But coloring edges with same color as source node or target node can be a good one. I think when `node_color_by` is present, setting `edge_color_by` to a special value like `'source_node_color'` is something we need.

**Comment by ericmjl** [comment]
@AlirezaH320 this is a great starter. With NetworkX, this functionality should be only applicable to directed graphs (i.e. graphs that inherit from `nx.DiGraph`).

I went digging in the codebase to see where the appropriate addition would be located. One thing for which this functionality has to hold true is that it must be composable with other things already present, and therefore it must be defined in one and only one place.

Categorically speaking, does this functionality best show up in the top-level API as a piece of "magic"? If so, then it sounds like the logical place to add this feature is inside `nxviz/api.py` [here](https://github.com/ericmjl/nxviz/blob/master/nxviz/api.py).

Alternatively, this could be thought of as a highlight or annotation, though those two are semantically intended to be for one-off things and not other things.

Apart from the three locations that I thought of above, are there alternatives where you think this should go?

For context, in case you're wondering why I'm being a bit more selective and thorough with the code placement here: the API refactor aims to follow the grammar of graphics' spirit, and I think I spent a lot of my paternity leave time thinking through the API architecture before going into the implementation. It felt very much like an applied category theory exercise. As such I'm simultaneously being curious about what "category" this feature request falls into while also being very careful not to break the categorical structure of the new API.

**Comment by AlirezaH320** [comment]
I understand your concern for code placement. I don't think `highlights` could be a good placement, because their purpose is highlighting some nodes or edges not the whole graph. `annotate` is also not good since it is mainly for text things. `api` could be a good placement. The "magic" can happen in the base function to check if graph is directed, `node_color_by` is present, and `edge_color_by` is set to our value, something like 'source_node_color'. then using some util like function to convert `node_color_by` to a valid hashable `edge_color_by` for `edge_line_func`.

**Comment by ericmjl** [comment]
@AlirezaH320 that sounds good. I'd be curious to see what the PR looks like, including tests. Be sure to note that node colors are always determined by the entire set of nodes' properties in a data-driven fashion. Therefore, the node table probably has to be used in order to get the colors that are necessary to set the edge properties.

Including this feature will introduce entanglement between node styling and edge styling, so definitely try to minimize any code entanglement between the two if you can. I'm curious to see how the PR will turn out - usually, I'd suggest a code sketch to help kickstart the idea, but it's quite late here and I'd like to head to bed soon. (My eyes are getting droopy typing this too.)

**Comment by AlirezaH320** [comment]
Hi @ericmjl
```python
et['source'].apply(nt[node_color_by].get)
or
et['target'].apply(nt[node_color_by].get)
```
This piece of code results a mapping from every edge to its source node color_by which will get us to the answer. But as you can see it needs `et`, `nt`, `edge_color_by` and `node_color_by` at the same time. At first I thought `api` is a good place but it seems the I was wrong. It's obvious that we need change the code in more than one place.

The only solution to do it in only one place is altering the graph with a new edge attribute and pass it to `edge_line_func` with that attribute as `color_by`.

What do you think? Should we change more than one place or alter the graph? Or any other Idea?

**Comment by ericmjl** [comment]
@AlirezaH320 that's great progress! :smile: Thanks for thinking it through.

Yes, what you mentioned is correct. There is also two other subtleties that need to be considered. Firstly, not all nodes necessarily have to be connected via an edge. Secondly, the colormap limits for edges are determined by _only_ the values present in the edge table. One place where coloring based on edges breaks down is if an unconnected node in the node set takes on a value more extreme than the values present in the suite of connected nodes. In this case, if we rely on annotating the edges' metadata with the node's values, we will have an inaccurate colormap for the edges.

Thus, it seems to me that the only way to enable coloring of the edges by nodes is to make multiple changes. What changes were you thinking of? 

At this point in time, the biggest idea running through my head is to leverage the lower-level API, particularly stuff in [`encodings.py`], which handle the encoding of data to colors. (It used to be called `aesthetics.py`, but a friend of mine, Fritz Lekschas, who did his PhD in data visualization, told me that encodings is the more accurate word to use.) The cleanest implementation I can think of looks something like passing in the node table's data into the `color_func` function and then taking the resultant function and applying it to the edge table's data. Though when to do this step, and where to put this functionality, is something I'm still a bit fuzzy on.

Btw, I'm liking how this problem is shaping up. There are code architecture questions to answer, which is always a nice intellectual challenge. I'd love to see your blog post, if you have a blog, about this issue after the PR is done! :smile:
